# Generated by Django 6.0.1 on 2026-01-24 17:31

import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocumentmodel',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
    ]
