# Generated by Django 6.0.1 on 2026-01-25 08:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_scanner', '0003_alter_pdfdocumentmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocumentmodel',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
